### ISSUE TITLE
`kitchen converge` fails on Ubuntu

### ISSUE THREAD

**Issue by krozett** [learn-chef/lcr-policyfiles-getstarted#3]
I managed to track the error down and found it was caused in `cookbooks/hardening/recipes/remediation.rb`:

`package "audit"`

This package does not exist on Ubuntu. It's `auditd`.
https://packages.ubuntu.com/xenial/auditd

**Comment by devopsdina** [comment]
Same is true for a successful centos-7 run, the package name should be `auditd`
